title       = "triviaapi2"
baseURL     = "https://triviaapi2-cli.tamnd.com/"
description = "A command line for triviaapi2."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/triviaapi2-cli"
